### ISSUE TITLE
Testing scenario links to scenario outside our repo

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml-katacoda#41]
https://github.com/digital-asset/daml-katacoda/blame/master/testing-daml-models/testing-with-scenarios/99_finish.md#L2

**Comment by ghost** [comment]
I fix this as part of the next PR that brings in the DAML script scenario.

**Comment by ghost** [comment]
Link now points to the right place, however the scenario is not yet online.

**Comment by ghost** [comment]
Fixed.
